language: java
jdk:
  - openjdk11

before_install:
  # install current snapshot of LibLaserCut (TODO remove after it's on central)
  - git clone --branch maven https://github.com/t-oster/LibLaserCut.git
  - pushd LibLaserCut && mvn install && popd
  # make sure we install legacy deps
  - mvn initialize

script: 
  - "./test.sh"
  - "mvn test"

