language: minimal
os: linux
dist: xenial

services:
  - docker

script: 
  - "./test.sh"
  - mkdir /tmp/out
  - chmod ugo+rwx /tmp/out
  - docker run -v /tmp/out:/app/output registry.gitlab.com/t-oster/visicutbuildservice
  - echo "Created out files:"
  - ls /tmp/out
  - ls /tmp/out/*
  - echo "Triggering build on download.visicut.org"
  - wget "https://vctrigger.thomas-oster.de/" -O-

deploy:
  provider: releases
  file: "/tmp/out/branch-master/**/*"
  cleanup: false
  on:
    tags: true

cache:
  directories:
  - $HOME/.m2
